### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by lastb0isct** [lf-/influx_nut#1]
```
python3 /etc/nut/influx_nut/influx_nut.py
Traceback (most recent call last):
  File "/etc/nut/influx_nut/influx_nut.py", line 341, in <module>
    cli()
  File "/etc/nut/influx_nut/influx_nut.py", line 336, in cli
    influx_creds=config['influx_creds'])
  File "/etc/nut/influx_nut/influx_nut.py", line 284, in update
    send_influx(influx_host, influx_db, datapoints, creds=influx_creds)
  File "/etc/nut/influx_nut/influx_nut.py", line 254, in send_influx
    data = b'\n'.join([str(datapoint).encode() for datapoint in datapoints])
  File "/etc/nut/influx_nut/influx_nut.py", line 254, in <listcomp>
    data = b'\n'.join([str(datapoint).encode() for datapoint in datapoints])
  File "/etc/nut/influx_nut/influx_nut.py", line 122, in __str__
    tag_str = ',' + ','.join(type(self)._keyvaluepairs(self.tags))
  File "/etc/nut/influx_nut/influx_nut.py", line 112, in _keyvaluepairs
    return ['{}={}'.format(k, v) for k, v in d.items()]
AttributeError: 'set' object has no attribute 'items'
```

(edit by maintainer: fixed formatting, next time use triple backticks instead of single :)

**Comment by lf-** [comment]
I'm really intrigued as to how this happened. The only value I can see `fields` having is a dictionary of hardcoded format, so the fact that a set got there is really interesting. Is the version you're running modified? Can you please provide the config (redact passwords if necessary) you're using?

**Comment by lastb0isct** [comment]
I've only added the variables.  Here is the config portion. 


    DEFAULT_CONFIG = {
    # interval between updates, in seconds
    'interval': 20,
    # ip/hostname of NUT server
    'nut_host': '127.0.0.1',
    # NUT port
    'nut_port': 3493,  
    # UPS name on that NUT server    
    'nut_ups': 'APC1500',

    # variables from NUT to send to influxdb
    # example in json:
    # "nut_vars": {
    #   "ups.realpower.nominal": {
    #        "type": "int",
    #        "measurement_name": "ups1_power"
    #   }
    # }
    'nut_vars': {
      "battery.charge": {
           "type": "int",
           "measurement_name": "1500_ups_charge"
      },
      "battery.runtime": {
           "type": "int",
           "measurement_name": "1500_ups_runtime"
      },
      "battery.voltage": {
           "type": "float",
           "measurement_name": "1500_ups_voltage"
      }
    },

    # proto://host:port of influxdb. Please don't add a trailing slash.
    'influx_host': 'http://127.0.0.1:8086',

    # database on the influx server
    'influx_db': 'UPS',

    # tags to add to influxdb measurements
    'influx_tags': {"APC1500"},

    # credentials for influxdb
    # example in json:
    # "influx_creds": ["user", "sekrit"]
    'influx_creds': []
    }

    #types allowed in nut_vars in the config
     CONFIG_TYPES = {
      'float': float,
      'int': int,
      'str': str,
      'bool': bool
    }

**Comment by lf-** [comment]
Your syntax is wrong on `'influx_tags'`, something like `{'a', 'b', 'c'}` is a set literal, but `{}` is an empty dictionary. `influx_tags` needs to be a dictionary, so you need it to be `{'prop_name': 'prop_value'}`.

You should probably use the config file system as the DEFAULT_CONFIG thing is just there as a default, with the intent of a JSON config file being used in addition. I realize it is not clear that that is the case in the README and I will see about fixing that.

**Comment by lastb0isct** [comment]
So the tags I should change to something else?  I'm not sure what the prop_name and prop_value are...

**Comment by lf-** [comment]
Sort of. In other words, what is in your config is a set (unordered collection of items), which is not the data format Influx uses for tags, and also why the code broke when confronted with it (because it doesn't behave like a dictionary/mapping). What Influx uses as tags is key-value pairs, so things like `{"ups_name": "APC1500"}`, or with a different UPS, `{"ups_name": "CyberPower"}` (on risk of being obtuse, these have both a property name and a value rather than just a value as in a set). You can later filter records by these tags in your queries.

**Comment by lastb0isct** [comment]
Ah, that did it! Thanks for the help =)
