### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by angdigi** [lf-/influx_nut#2]
Hi - Tried running this script but get the following message. Any help would be appreciated.

File "/tmp/user.scripts/tmpScripts/influx_nut/script", line 64
def __init__(self, measurement, fields, tags: dict = {},
^
SyntaxError: invalid syntax

**Comment by lf-** [comment]
You need to use a version of Python new enough to have support for type annotations (minimum 3.5). What's probably happening is that you're running it with Python 2 inadvertently because `python` is Python 2 on most distributions. So you should run it with `python3`.

**Comment by angdigi** [comment]
Thank you. That was it.

I had to install the 'requests' module, but after doing that I received the following message.

usage: script [-h] [--config CONFIG]
script: error: unrecognized arguments:

**Comment by lf-** [comment]
There's nothing under that with more info on the arguments which are wrong? You should probably still be good to go, just copy the configuration template from the readme into a file, fix the settings for your use and then point to it with --config.

**Comment by angdigi** [comment]
That's all I get. I did edit the config in the script directly, though. Is that the issue?

**Comment by lf-** [comment]
It isn't designed to be configured directly in the script, but another user seems to have it working that way. Can you please provide any modifications done to the script and config files so I can further diagnose this?

**Comment by angdigi** [comment]
My mistake.

Sure thing. I attached the script with the modifications I made. That's the only file I was using.
[influx_nut script.txt](https://github.com/lf-/influx_nut/files/2452577/influx_nut.script.txt)

**Comment by lf-** [comment]
Hm. Your shebang should be `/usr/bin/python3` obviously, but other than that I can't see any issue. Try putting the line `import sys; print(sys.argv)` at the start of `cli()` and reporting the result.

I tried your version with the command line `./influx_nut.py` and the argument parsing goes through just fine.

**Comment by angdigi** [comment]
Here is the output after adding that line

> Script location: /tmp/user.scripts/tmpScripts/influx_nut/script
Note that closing this window will abort the execution of this script
usage: script [-h] [--config CONFIG]
script: error: unrecognized arguments: 
['/tmp/user.scripts/tmpScripts/influx_nut/script', '']

Attached is current script
[influx_nut script.txt](https://github.com/lf-/influx_nut/files/2456992/influx_nut.script.txt)

Also, tried /usr/bin/python3 but didn't help. Here is the output..

> Script location: /tmp/user.scripts/tmpScripts/influx_nut/script
Note that closing this window will abort the execution of this script
/tmp/user.scripts/tmpScripts/influx_nut/script: line 3: import: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 4: import: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 5: import: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 6: import: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 7: import: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 8: import: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 9: from: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 11: import: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 14: __doc__: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 16: DEFAULT_CONFIG: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 18: interval:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 20: nut_host:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 22: nut_port:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 24: nut_ups:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 34: nut_vars:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 37: influx_host:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 40: influx_db:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 43: influx_tags:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 48: influx_creds:: command not found
/tmp/user.scripts/tmpScripts/influx_nut/script: line 49: syntax error near unexpected token `}'
/tmp/user.scripts/tmpScripts/influx_nut/script: line 49: `}'

So I kept it as-is.

**Comment by lf-** [comment]
Hm, so what's happening is that somehow an empty command line argument is being introduced. How are you running the program?

Here's an example command line that would cause this: `python3 influx_nut.py ''`.

Now, it appears that you're using unraid which might be the source of the blank command line argument. I don't know if you can fix it with the GUI or indeed if there is a better way to run daemon-type scripts as I have no experience with the software.

For a (pretty bad) hack to fix it for the immediate term, insert the line `del sys.argv[-1]` after the imports at the top of the file. This will remove the last item in the command line arguments before any of influx_nut sees it.

**Comment by lf-** [comment]
I'm closing this as I assume it has been fixed. I'm still not sure what Unraid is stuffing in your command line arguments, but that's fine.

**Comment by angdigi** [comment]
Sorry for the lack of response. I stopped using Grafana after I discovered Netdata but I appreciate the help.
